name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Harbor
      run: echo "B4teau123!" | docker login harbor.kakor.ovh -u ipi --password-stdin

    - name: Build Docker image
      run: docker build -t harbor.kakor.ovh/ipi/groupe3:${{ github.sha }} .

    - name: Push Docker image
      run: docker push harbor.kakor.ovh/ipi/groupe3:${{ github.sha }}

  trivy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

    - name: Run Trivy scan
      run: trivy image harbor.kakor.ovh/ipi/groupe3:${{ github.sha }}
      continue-on-error: true


    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      continue-on-error: true
      with:
        image-ref: 'harbor.kakor.ovh/ipi/groupe3:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, trivy]

    steps:
    - name: Login to OpenShift
      run: |
        oc login https://api.openshift.kakor.ovh:6443 --token=${{ secrets.OPENSHIFT_TOKEN }}

    - name: Deploy to OpenShift
      run: oc apply -f kubernetes-manifest/deployment.yaml
